### ISSUE TITLE
fwrite problem with ECS and ElastiCache

### ISSUE THREAD

**Issue by manuelbcd** [cheprasov/php-redis-lock#9]
Concurrent instances running in AWS on Ubuntu 14.04 with PHP 7.1 polling locks against ElastiCache service.

Some times we get this error:
`PHP Warning: fwrite(): supplied resource is not a valid stream resource in /var/www/html/vendor/cheprasov/php-redis-client/src/RedisClient/Connection/StreamConnection.php on line 113`

This appears to be random and I cannot find a relationship with high loads or stress periods.

The code that I'm using:

```
    public function acquireLock(string $key, $waitTime = 0, $sleep = null): bool
    {
        // Check RedisLock handler instance
        if (null !== $this->redisLock) {
            if ($this->redisClient->get($key)) {
                IMSUtils::getLogger()
                        ->warning(static::MSG_LOCK_COULD_NOT_BE_ACQUIRED . ' This thread has not released a previous self lock.');

                return false;
            }
            // If lock exist, but no entry in Redis. Might be a zombie process, we release the lock first.
            $this->redisLock->release();
        }
        // Create the lock
        $this->redisLock = new RedisLock($this->redisClient, $key, RedisLock::FLAG_DO_NOT_THROW_EXCEPTIONS);
        // Acquire the lock
        if (!$this->redisLock->acquire(static::LOCK_TIMEOUT, $waitTime, $sleep)) {
            IMSUtils::getLogger()->warning(static::MSG_LOCK_COULD_NOT_BE_ACQUIRED);

            return false;
        }

        return true;
    }
```
Any idea about what could be happening?

Thank you in advance

**Comment by cheprasov** [comment]
Hey @manuelbcd 
Unfortunately, I have no idea. But I will try to find out. 
Do you use any multi-threading in PHP on the server?
Also, please, see this https://github.com/twitter/twemproxy/issues/18
Is it helpful for you?

**Comment by manuelbcd** [comment]
Hi,
Negative. We'll include multi threading in a further step but the script is linear right now  (launch command, whait for execution to finish and launch CLI command again) .

The concurrency is on multiple docker orchestrated by ECS agent right now. 
The worst thing is that I'm unable to reproduce it even with 4 containers at the same time polling for redis lock... however in normal execution it happens some times.

Anyhow thank you for the response. If I can have more information I will reopen the issue.

**Comment by manuelbcd** [comment]
@cheprasov It seems that there are eventual problems with CNAMES in AWS containers.  I cannot find other explanation.
Thanks for your support.

Regards
